development:
  adapter: postgresql
  encoding: unicode
  database: my_covtest_hub_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: my_covtest_hub_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: my_covtest_hub_production
  pool: 5